name: neosocius
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  firebase_core: ^2.26.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.12.0
  geolocator: ^10.1.0
  permission_handler: ^11.3.0
  flutter_map_heatmap: ^0.0.8
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true